### PR TITLE
action.d/*ipset*: make maxelem ipset option configurable through banaction arguments

### LINKED ISSUE #3549: [BR]: ipsets created by firewallcmd-ipset action only ban up to 65536 IPs
### Environment:

- Fail2Ban version: 1.0.2-2
- OS, including release name/version : Debian 12
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

```ini
# /etc/fail2ban/jail.local
[DEFAULT]
bantime   = 1year
banaction = firewallcmd-ipset[actiontype=<multiport>,blocktype=DROP]
banaction_allports = firewallcmd-ipset[actiontype=<allports>,blocktype=DROP]
```

### The issue:

On hosts where `bantime` is set to a long duration (e.g. 1 year) and/or subject to constant bruteforce attempts, and where the `firewallcmd-ipset` is used as `banaction`, the number of banned IPs quickly exceeds the max number of elements in the `ipset` created by the action. This number is `65536`, which is the default when creating an ipset without using the `maxelem NUMBER` option. 

When this limit is reached, no more IPs can be added to the ipset and offenders are no longer effectively banned:

```
fail2ban.utils          [433696]: ERROR   7f3a01e05ed0 -- exec: ipset -exist add f2b-sshd 1.2.3.4/24 timeout 0
fail2ban.utils          [433696]: ERROR   7f3a01e05ed0 -- stderr: 'ipset v7.17: Hash is full, cannot add more elements'
fail2ban.utils          [433696]: ERROR   7f3a01e05ed0 -- returned 1
fail2ban.actions        [433696]: ERROR   Failed to execute ban jail 'sshd' action 'firewallcmd-ipset' info 'ActionInfo({'ip': '1.2.3.4/24', 'family': 'inet4', 'fid': <function Actions.ActionInfo.<lambda> at 0x7f3a03fb9e40>, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7f3a03fba5c0>})': Error banning 1.2.3.4/24
```

#### Steps to reproduce

- Set up a jail with a high rate of positive matches (e.g. `sshd` on a publicly exposed SSH server, or jail+filter that bans hosts scanning for `wp_admin/`, `.git/config` on webserver virtualhosts, etc.) and/or long ban time
- Set `firewallcmd-ipset` as `banaction` for the jail (or as default `banaction`)
- Wait until the number of banned hosts reaches 65536

#### Expected behavior

The jail should keep doing its job regardless of the number of IP addresses added to it. There are 2³² IPv4 addresses and while I do not expect to ever ban most of them, a jail like the one I mentioned above will definitely exceed 65536 banned IPs after some time.

I suggest making the `maxelem` ipset option configurable through banaction options (e.g. `banaction = firewallcmd-ipset[actiontype=<multiport>,blocktype=DROP,maxelem=1000000]`, _or_ setting a high value for this option by default.

#### Observed behavior

- Error message above in fail2ban logs
- ipset stops growing, new offenders not banned

#### Any additional information

- This might also affect other `ipset`-based actions? (did not check)
- There is a workaround which involves editing the following lines in `/etc/fail2ban/action.d/firewallcmd-ipset.conf` (add `maxelem 1000000` option):

```ini
[ipstype_ipset]
actionstart = ipset -exist create <ipmset> hash:ip timeout <default-ipsettime> maxelem 1000000 <familyopt>
```
```ini
[ipstype_firewalld]
actionstart = firewall-cmd --direct --new-ipset=<ipmset> --type=hash:ip --option=timeout=<default-ipsettime> --option=maxelem=1000000 <firewalld_familyopt>
```

However it is not practical, because it involves editing a config/action file provided by fail2ban (as far as I know there is no way to override these specific settings from a `.local` or `.d/*conf` file?).

Filing this as a bug report because it makes such jails ineffective (and I did not notice this problem for a while, and stumbled on it while manually checking fail2ban logs), and the workaround for it is not optimal.

As far as I know, and after checking the [ipset manpage](https://manpages.debian.org/bullseye/ipset/ipset.8.en.html) there are no downsides to a larger `maxelem` value, it does not appear to affect memory usage like the `hashsize` or `bucketsize` options do.

### Configuration, dump and another helpful excerpts

Relevant info provided above.

#### Any customizations done to /etc/fail2ban/ configuration

Relevant info provided above.

#### Relevant parts of /var/log/fail2ban.log file:

```
fail2ban.utils          [433696]: ERROR   7f3a01e05ed0 -- exec: ipset -exist add f2b-ssh 1.2.3.4/24 timeout 0
fail2ban.utils          [433696]: ERROR   7f3a01e05ed0 -- stderr: 'ipset v7.17: Hash is full, cannot add more elements'
fail2ban.utils          [433696]: ERROR   7f3a01e05ed0 -- returned 1
fail2ban.actions        [433696]: ERROR   Failed to execute ban jail 'sshd' action 'firewallcmd-ipset' info 'ActionInfo({'ip': '1.2.3.4/24', 'family': 'inet4', 'fid': <function Actions.ActionInfo.<lambda> at 0x7f3a03fb9e40>, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7f3a03fba5c0>})': Error banning 1.2.3.4/24
```

#### Relevant lines from monitored log files:

Any line that matches a jail with high positives rate.

Thanks a lot for maintaining fail2ban.

### PR DESCRIPTION
**Pull request by nodiscc**
- previously there was no way to override this value and ipsets would stop being updated when full (Hash is full, cannot add more elements)
- preserve ipset's default value of 65536
- update tests
- Closes #3549

--------------

Before submitting your PR, please review the following checklist:

- [x] **CHOOSE CORRECT BRANCH**: if filing a bugfix/enhancement
      against certain release version, choose `0.9`, `0.10` or `0.11` branch,
      for dev-edition use `master` branch
- [ ] **CONSIDER adding a unit test** if your PR resolves an issue
- [x] **LIST ISSUES** this PR resolves
- [x] **MAKE SURE** this PR doesn't break existing tests
- [x] **KEEP PR small** so it could be easily reviewed.
- [x] **AVOID** making unnecessary stylistic changes in unrelated code
- [ ] **ACCOMPANY** each new `failregex` for filter `X` with sample log lines
      within `fail2ban/tests/files/logs/X` file

------------------

- I get a few test failures locally when running `./bin/fail2ban-testcases`, these failures also occur on `master`
- Should I backport this to the `1.0` branch?

### CODE REVIEW

File: config/action.d/iptables-ipset-proto4.conf [hunk 1]
```diff
@@ -27,7 +27,7 @@ before = iptables.conf
 # Notes.:  command executed on demand at the first ban (or at the start of Fail2Ban if actionstart_on_demand is set to false).
 # Values:  CMD
 #
-actionstart = ipset --create f2b-<name> iphash
+actionstart = ipset --create f2b-<name> maxelem <maxelem> iphash
```
Comment (sebres) [inline config/action.d/iptables-ipset-proto4.conf:30]: However I'm unsure whether ipset protocol 4 (ipset v4.2) supports maxelm or the option is implemented in this way.
But since it is totally obsolete action it is OK (I'll remove it later anyway)...

**Review by sebres — APPROVED** [review]

**Comment by sebres** [comment]
Thx for the PR, I'll merge it soon.

> I get a few test failures locally when running ./bin/fail2ban-testcases, these failures also occur on master

which failures exactly?

> Should I backport this to the 1.0 branch?

Nope.

**Comment by nodiscc** [comment]
> which failures exactly?

```
~/GIT/fail2ban (master=)$ git rev-parse HEAD
bbca81f34cb8104a71f6508dba4c7e2d776ac7fe
~/GIT/fail2ban (master=)$ ./bin/fail2ban-testcases 
Fail2ban 1.1.0.dev1 test suite. Python 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]. Please wait...
.............................ss.............................................................................................................................................s................................................s...............................................................F................F...F.FF..............................................................................................................................
..............................s.......................................
======================================================================
FAIL: testGetFailuresUseDNS (fail2ban.tests.filtertestcase.GetFailures)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/filtertestcase.py", line 1930, in testGetFailuresUseDNS
    _assert_correct_last_attempt(self, filter_, output)
  File "./fail2ban/tests/filtertestcase.py", line 193, in _assert_correct_last_attempt
    utest.assertEqual(len(found), len(output))
AssertionError: 2 != 3

======================================================================
FAIL: testIPAddr_CompareDNS (fail2ban.tests.filtertestcase.DNSUtilsNetworkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/filtertestcase.py", line 2359, in testIPAddr_CompareDNS
    self.assertTrue(IPAddr("2606:2800:220:1:248:1893:25c8:1946").isInNet(ips))
AssertionError: False is not true

======================================================================
FAIL: testIpToIp (fail2ban.tests.filtertestcase.DNSUtilsNetworkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/utils.py", line 575, in assertSortedEqual
    _assertSortedEqual(a, b, level, nestedOnly, key)
  File "./fail2ban/tests/utils.py", line 552, in _assertSortedEqual
    raise ValueError('%r != %r' % (a, b))
ValueError: set() != ['2606:2800:220:1:248:1893:25c8:1946']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./fail2ban/tests/filtertestcase.py", line 2188, in testIpToIp
    self.assertSortedEqual(ips, [s])
  File "./fail2ban/tests/utils.py", line 582, in assertSortedEqual
    self.fail(msg)
AssertionError: set() != ['2606:2800:220:1:248:1893:25c8:1946']
- set()
+ ['2606:2800:220:1:248:1893:25c8:1946']

======================================================================
FAIL: testTextToIp (fail2ban.tests.filtertestcase.DNSUtilsNetworkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/utils.py", line 575, in assertSortedEqual
    _assertSortedEqual(a, b, level, nestedOnly, key)
  File "./fail2ban/tests/utils.py", line 552, in _assertSortedEqual
    raise ValueError('%r != %r' % (a, b))
ValueError: {'93.184.216.34'} != ['93.184.216.34', '2606:2800:220:1:248:1893:25c8:1946']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./fail2ban/tests/filtertestcase.py", line 2180, in testTextToIp
    self.assertSortedEqual(res, ['93.184.216.34', '2606:2800:220:1:248:1893:25c8:1946'])
  File "./fail2ban/tests/utils.py", line 582, in assertSortedEqual
    self.fail(msg)
AssertionError: {'93.184.216.34'} != ['93.184.216.34', '2606:2800:220:1:248:1893:25c8:1946']
- {'93.184.216.34'}
+ ['93.184.216.34', '2606:2800:220:1:248:1893:25c8:1946']

======================================================================
FAIL: testUseDns (fail2ban.tests.filtertestcase.DNSUtilsNetworkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/utils.py", line 575, in assertSortedEqual
    _assertSortedEqual(a, b, level, nestedOnly, key)
  File "./fail2ban/tests/utils.py", line 552, in _assertSortedEqual
    raise ValueError('%r != %r' % (a, b))
ValueError: {'93.184.216.34'} != ['93.184.216.34', '2606:2800:220:1:248:1893:25c8:1946']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./fail2ban/tests/filtertestcase.py", line 2163, in testUseDns
    self.assertSortedEqual(res, ['93.184.216.34', '2606:2800:220:1:248:1893:25c8:1946'])
  File "./fail2ban/tests/utils.py", line 582, in assertSortedEqual
    self.fail(msg)
AssertionError: {'93.184.216.34'} != ['93.184.216.34', '2606:2800:220:1:248:1893:25c8:1946']
- {'93.184.216.34'}
+ ['93.184.216.34', '2606:2800:220:1:248:1893:25c8:1946']

----------------------------------------------------------------------
Ran 506 tests in 25.202s

FAILED (failures=5, skipped=5)
```

(Debian 11)

**Comment by sebres** [comment]
Since all that tests are DNS related tests and affected by missed IPv6 address, I guess your host where you test it or your DNS server don't support IPv6...
Can you confirm it?
```diff
  $ cd /projects/fail2ban
  $ PYTHONPATH=. python3 -c 'from fail2ban.server.ipdns import DNSUtils; print(DNSUtils.IPv6IsAllowed())'
- False
+ True
```
We can surely rewrite this tests to consider such constellation (or skip them for the case `DNSUtils.IPv6IsAllowed()` is false), but...
You could also test f2b with `--no-network` switch (I typically test it with `-fn` what is faster and cover more than 95% of code base, but 100% of banning facilities and complete fail2ban configuration).

**Comment by sebres** [comment]
Never mind, 35af8b6d5dc7aa224e636cbfd5a8cacac411a8ce must now fix the tests for systems without IPv6 support.

**Comment by nodiscc** [comment]
>  I guess your host where you test it or your DNS server don't support IPv6... Can you confirm it?

Can confirm, IPv6 disabled on this host

> Never mind, https://github.com/fail2ban/fail2ban/commit/35af8b6d5dc7aa224e636cbfd5a8cacac411a8ce must now fix the tests for systems without IPv6 support.

Just checked, all tests passing now. Well done, thanks again.
