### PR TITLE
Fix support for Asterisk security log

### LINKED ISSUE #988: asterisk 13 & fail2ban -  log is not working
Asterisk 13.1.0
Fail2Ban v0.8.14

;logger.conf
dateformat=%F %T
security => security

./fail2ban-regex /opt/env2/var/log/asterisk/security /etc/fail2ban/filter.d/asterisk.conf
-empty

[root@goip16 bin]# tail /opt/env2/var/log/asterisk/security
[2015-03-11 22:21:07] SECURITY[999] res_security_log.c: SecurityEvent="ChallengeSent",EventTV="2015-03-11T22:21:07.504+0200",Severity="Informational",Service="SIP",EventVersion="1",AccountID="5008",SessionID="0xb31f5c9c",LocalAddress="IPV4/UDP/77.91.132.4/5060",RemoteAddress="IPV4/UDP/5.248.228.46/5060",Challenge="384d9078"
[2015-03-11 22:21:07] SECURITY[999] res_security_log.c: SecurityEvent="SuccessfulAuth",EventTV="2015-03-11T22:21:07.525+0200",Severity="Informational",Service="SIP",EventVersion="1",AccountID="5008",SessionID="0xb31f5c9c",LocalAddress="IPV4/UDP/77.91.132.4/5060",RemoteAddress="IPV4/UDP/5.248.228.46/5060",UsingPassword="1"
[2015-03-11 22:21:08] SECURITY[999] res_security_log.c: SecurityEvent="ChallengeSent",EventTV="2015-03-11T22:21:08.017+0200",Severity="Informational",Service="SIP",EventVersion="1",AccountID="501",SessionID="0xb7507214",LocalAddress="IPV4/UDP/77.91.132.4/5060",RemoteAddress="IPV4/UDP/77.122.109.14/51544",Challenge="15c56e34"
[2015-03-11 22:21:08] SECURITY[999] res_security_log.c: SecurityEvent="ChallengeSent",EventTV="2015-03-11T22:21:08.033+0200",Severity="Informational",Service="SIP",EventVersion="1",AccountID="5007",SessionID="0xb390f1f4",LocalAddress="IPV4/UDP/77.91.132.4/5060",RemoteAddress="IPV4/UDP/5.248.228.46/5060",Challenge="720f8bd7"
[2015-03-11 22:21:08] SECURITY[999] res_security_log.c: SecurityEvent="InvalidPassword",EventTV="2015-03-11T22:21:08.045+0200",Severity="Error",Service="SIP",EventVersion="2",AccountID="501",SessionID="0xb7507214",LocalAddress="IPV4/UDP/77.91.132.4/5060",RemoteAddress="IPV4/UDP/77.122.109.14/51544",Challenge="15c56e34",ReceivedChallenge="15c56e34",ReceivedHash="0492a7b827a27a7e1d9473de79a1ee6e"
[2015-03-11 22:21:08] SECURITY[999] res_security_log.c: SecurityEvent="SuccessfulAuth",EventTV="2015-03-11T22:21:08.056+0200",Severity="Informational",Service="SIP",EventVersion="1",AccountID="5007",SessionID="0xb390f1f4",LocalAddress="IPV4/UDP/77.91.132.4/5060",RemoteAddress="IPV4/UDP/5.248.228.46/5060",UsingPassword="1"
[2015-03-11 22:21:08] SECURITY[999] res_security_log.c: SecurityEvent="ChallengeSent",EventTV="2015-03-11T22:21:08.473+0200",Severity="Informational",Service="SIP",EventVersion="1",AccountID="5006",SessionID="0xb7526d74",LocalAddress="IPV4/UDP/77.91.132.4/5060",RemoteAddress="IPV4/UDP/5.248.228.46/5060",Challenge="4609ad0c"
[2015-03-11 22:21:08] SECURITY[999] res_security_log.c: SecurityEvent="SuccessfulAuth",EventTV="2015-03-11T22:21:08.495+0200",Severity="Informational",Service="SIP",EventVersion="1",AccountID="5006",SessionID="0xb7526d74",LocalAddress="IPV4/UDP/77.91.132.4/5060",RemoteAddress="IPV4/UDP/5.248.228.46/5060",UsingPassword="1"
[2015-03-11 22:21:08] SECURITY[999] res_security_log.c: SecurityEvent="ChallengeSent",EventTV="2015-03-11T22:21:08.682+0200",Severity="Informational",Service="SIP",EventVersion="1",AccountID="5005",SessionID="0xb75d21cc",LocalAddress="IPV4/UDP/77.91.132.4/5060",RemoteAddress="IPV4/UDP/5.248.228.46/5060",Challenge="002d4064"
[2015-03-11 22:21:08] SECURITY[999] res_security_log.c: SecurityEvent="SuccessfulAuth",EventTV="2015-03-11T22:21:08.705+0200",Severity="Informational",Service="SIP",EventVersion="1",AccountID="5005",SessionID="0xb75d21cc",LocalAddress="IPV4/UDP/77.91.132.4/5060",RemoteAddress="IPV4/UDP/5.248.228.46/5060",UsingPassword="1"

[root@goip16 bin]# iptables -L -n
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
fail2ban-ASTERISK  all  --  0.0.0.0/0            0.0.0.0/0           
fail2ban-SSH  tcp  --  0.0.0.0/0            0.0.0.0/0           tcp dpt:22 

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain fail2ban-ASTERISK (1 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           

Chain fail2ban-SSH (1 references)
target     prot opt source               destination         
REJECT     all  --  125.88.17.156        0.0.0.0/0           reject-with icmp-port-unreachable 
RETURN     all  --  0.0.0.0/0            0.0.0.0/0

### PR DESCRIPTION
**Pull request by ipoddubny**
This pull request fixes the following issues:
- EventTV in ISO8601 format (Asterisk 12+)
- PJSIP writes SIP Call-Id header as SessionID (only hex pointers used by chan_sip and manager were supported)
- "\<unknown\>" in AccountID was not matched
- Challenge may contain '/' character and may come without ReceivedChallenge but with Response and ExpectedResponse
- Added support for WebSocket protocol events (thanks to @kcormier)

Closes #988

### CODE REVIEW

File: config/filter.d/asterisk.conf [hunk 1]
```diff
@@ -23,7 +25,7 @@ failregex = ^(%(__prefix_line)s|\[\]\s*)%(log_prefix)s Registration from '[^']*'
...
             ^(%(__prefix_line)s|\[\]\s*)%(log_prefix)s Failed to authenticate (user|device) [^@]+@<HOST>\S*$
             ^(%(__prefix_line)s|\[\]\s*)%(log_prefix)s hacking attempt detected '<HOST>'$
-            ^(%(__prefix_line)s|\[\]\s*)%(log_prefix)s SecurityEvent="(FailedACL|InvalidAccountID|ChallengeResponseFailed|InvalidPassword)",EventTV="[\d-]+",Severity="[\w]+",Service="[\w]+",EventVersion="\d+",AccountID="\d*",SessionID="0x[\da-f]+",LocalAddress="IPV[46]/(UD|TC)P/[\da-fA-F:.]+/\d+",RemoteAddress="IPV[46]/(UD|TC)P/<HOST>/\d+"(,Challenge="\w+",ReceivedChallenge="\w+")?(,ReceivedHash="[\da-f]+")?(,ACLName="\w+")?$
+            ^(%(__prefix_line)s|\[\]\s*)%(log_prefix)s SecurityEvent="(FailedACL|InvalidAccountID|ChallengeResponseFailed|InvalidPassword)",EventTV="([\d-]+|%(iso8601)s)",Severity="[\w]+",Service="[\w]+",EventVersion="\d+",AccountID="(\d*|<unknown>)",SessionID="\S+",LocalAddress="IPV[46]/(UDP|TCP|WS)/[\da-fA-F:.]+/\d+",RemoteAddress="IPV[46]/(UDP|TCP|WS)/<HOST>/\d+"(,Challenge="[\w/]+")?(,ReceivedChallenge="\w+")?(,Response="\w+",ExpectedResponse="\w*")?(,ReceivedHash="[\da-f]+")?(,ACLName="\w+")?$
```
Comment (yarikoptic) [inline config/filter.d/asterisk.conf]: Almost perfect -- thanks!!!  I have only minor reservation against having a bit too loose `\S+` here since everything in these log lines "tags" is without spaces... not sure if injection could happen but I would prefer to be as specific as possible.  In this case it should be without ", so what about smth like ```[^"\s,]+```?  great that you have a test case already . Cheers

Comment (ipoddubny) [inline config/filter.d/asterisk.conf]: I've done more thorough testing, and it seems like it may contain spaces, quotes... basically everything except line breaks.

Here's an example of a SIP message that was correctly handled:
```
REGISTER sip:127.0.0.1 SIP/2.0
Via: SIP/2.0/UDP 127.0.1.1:5061;branch=z9hG4bK-28514-1-0
Max-Forwards: 70
From: "sipp" <sip:70000180@127.0.0.1>;tag=1
To: "sipp" <sip:70000180@127.0.0.1>
Call-ID: 123",LocalAddress="IPV4/UDP/127.0.0.1/5060",RemoteAddress="IPV4/UDP/5.6.7.8/1111"
CSeq: 7 REGISTER
Contact: <sip:sipp@127.0.1.1:5061>
Expires: 3600
Content-Length: 0
User-Agent: SIPp
```
...and here's a line in security log that Asterisk writes:
```
[May 25 07:35:02] SECURITY[6988] res_security_log.c: SecurityEvent="InvalidAccountID",EventTV="2015-05-25T07:35:02.729+0300",Severity="Error",Service="PJSIP",EventVersion="1",Accou
ntID="70000180",SessionID="123",LocalAddress="IPV4/UDP/127.0.0.1/5060",RemoteAddress="IPV4/UDP/5.6.7.8/1111"",LocalAddress="IPV4/UDP/176.11.188.16/5060",RemoteAddress="IPV4/UDP/12
7.0.0.1/5061"
```

So, the regexp for SessionID should be even looser and I don't see any alternative to ``.+``.

**Comment by yarikoptic** [comment]
well -- I was about to reply that even if we miss some malicious attempts it would still better to be "safe than sorry" by missing those while keeping failregex solid in avoiding possible injections, which usually happens when ```.*``` etc is used within failregex.  But looking at the trailer where HOST is specified, it seems to remain stringent enough to not allow arbitrary placement of an IP within.  Just to be safe -- please add a test case where ```RemoteAddress="IPV[46]/(UDP|TCP|WS)/<HOST>/\d+"``` with some victim IP is injected within SessionID so we could catch such case happen we customize/relax this failregex more in the future

**Comment by yarikoptic** [comment]
ah -- you already did!! ;)

**Comment by yarikoptic** [comment]
actually nope -- you did for LocalAddress not RemoteAddress ;-)
and I wonder why those badips tests fail for you on travis but not for other PRs

**Comment by ipoddubny** [comment]
Well, the test line
```
[2015-05-25 07:21:48] SECURITY[6988] res_security_log.c: SecurityEvent="InvalidAccountID",EventTV="2015-05-25T07:21:48.275+0300",Severity="Error",Service="PJSIP",EventVersion="1",AccountID="70000180",SessionID="",LocalAddress="IPV4/UDP/127.0.0.1/5060",RemoteAddress="IPV4/UDP/5.6.7.8/1111"",LocalAddress="IPV4/UDP/1.2.3.4/5060",RemoteAddress="IPV4/UDP/10.250.251.252/5061"
```
contains two LocalAddresses and two RemoteAddresses, but only the last one is matched.

As expression is bound to the end of string with $, honestly I don't see any possibility for injections here. Whatever attacker insterts in SessionID, there will always be some stuff at the end of the line that would contains his real IP (line breaks don't pass, I've checked that).

**Comment by yarikoptic** [comment]
sorry -- I have overlooked that it does contain both already.
