### PR TITLE
Add codespell: workflow, config and fix typos it finds

### LINKED ISSUE #2595: Codespell report for the "fail2ban" project
As administrator of the FOSS server fossies.org I have just created for testing purposes a codespell based analysis for the new `fail2ban` release "0.11.1":

https://fossies.org/linux/misc/fail2ban/codespell.html

That version-independent (not linked) URL should always redirect to the last report (if available), so currently to

https://fossies.org/linux/misc/fail2ban-0.11.1.tar.gz/codespell.html

Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (ignored) please inform me if you find more of them so that I can force a new improved check if applicable.

Just for information there are also two supplemental pages https://fossies.org/linux/misc/fail2ban/codespell_conf.html (showing some used "codespell" configurations) and https://fossies.org/linux/misc/fail2ban/codespell_fps.html (showing all resulting obvious "False Positives").

If meaningful I could also generate in a special Fossies "test" folder a supplemental codespell analysis for the last `fail2ban` master version.

### PR DESCRIPTION
**Pull request by yarikoptic**
Long time no commit from yours truly.  I was introducing codespell to a good number of projects and eventually recalled fail2ban!  I was afraid it would be non-trivial due to all the regexes etc, but it seems that codespell is damn robust and I needed to provide only a single workaround regex.

Before submitting your PR, please review the following checklist:

- [x] **CHOOSE CORRECT BRANCH**: if filing a bugfix/enhancement
      against certain release version, choose `0.9`, `0.10` or `0.11` branch,
      for dev-edition use `master` branch.  In principle could be against some released branch but since renamed `substition` to `substitution` decided to stick to master
- [ ] **MAKE SURE** this PR doesn't break existing tests
- [x] **KEEP PR small** so it could be easily reviewed - just slightly over 50 files ;) I had larger ones.
- [x] **AVOID** making unnecessary stylistic changes in unrelated code

Closes #2595 and Closes #3558 (supersedes)

### CODE REVIEW

File: config/filter.d/postfix.conf [hunk 1]
```diff
@@ -17,7 +17,7 @@ _pref = [A-Z]{4}
 prefregex = ^%(__prefix_line)s<mdpr-<mode>> <F-CONTENT>.+</F-CONTENT>$
 
 # Extended RE for normal mode to match reject by unknown users or undeliverable address, can be set to empty to avoid this:
-exre-user = |[Uu](?:ser unknown|ndeliverable address)
+exre-user = |(?:[Uu]ser unknown|[Uu]ndeliverable address)
```
Comment (sebres) [inline config/filter.d/postfix.conf:20]: Don't think this'd be a part of spelling/typos fixing branch...
Moreover why it must be changed at all? Because otherwise "stupid" spelling tool bothers on `ndeliverable`?

**Review by sebres — COMMENTED** [review]
Just as reference few related issues/PRs: #1896, #2595 and #3558

File: .github/workflows/codespell.yml [hunk 2]
```diff
@@ -0,0 +1,22 @@
+---
+name: Codespell
+
+on:
+  push:
+    branches: [master]
+  pull_request:
+    branches: [master]
```
[the remark this answers is not in the document]
Comment (sebres) [reply .github/workflows/codespell.yml:8]: I think master is fully enough to continuously waste GHA resources with spelling check.

File: config/filter.d/postfix.conf (hunk 1 above)
Comment (yarikoptic) [reply config/filter.d/postfix.conf:20]: yeah -- I made it into a separate commit even for that reason so we get a clear dedicated description. It is the `ser` which is a possible typo for `set` (and may be smth else).  So indeed, it is a code change to please `codespell`. But you are the boss -- if you like, I can just ignore `ser` (and thus we could let some typos in) globally and drop that commit.

**Comment by yarikoptic** [comment]
> Just as reference few related issues/PRs: #1896, #2595 and #3558

see -- you can't escape `codespell` -- it will keep hunting you down. Let's get over with it!!! ;)

File: config/filter.d/postfix.conf (hunk 1 above)
Comment (sebres) [reply config/filter.d/postfix.conf:20]: Ignore globally or is there some pragma doing the job for single line? (Just to know how it's possible)

Comment (yarikoptic) [reply config/filter.d/postfix.conf:20]: there is https://github.com/codespell-project/codespell/issues/1212 which is still open but as a comment there [says](https://github.com/codespell-project/codespell/issues/1212#issuecomment-1744768533) it is trivial to workaround by tuning regex-skip and defining custom pragma. So let's code for a line with `codespell-ignore` in it to be ignored. I will add that now and drop that commit.

Comment (yarikoptic) [reply config/filter.d/postfix.conf]: I have done that, will mark resolved

**Comment by yarikoptic** [comment]
Tests pass... Merge?

**Comment by sebres** [comment]
If you mean we really need it, then do that...
I already expressed my opinion to spelling (especially spell vs python) many times... However fail2ban project can probably cope with that (since its codebase is relative medium-sized and straightforward), and all the forks should solve the possible conflicts once.

**Comment by yarikoptic** [comment]
ok, let's do it then in a good memory of Yarik so he never comes back with yet another spell'ing PR ;)  I do not think there would even be that huge number of conflicts (I wonder if there is some service to give estimates on that).  So By the power vested in me by God and man, I pronounce you 9fc754ceeac900f2480694ccf941d20791c3d039 and 8ef0d3c7a91e8771e5d075ff62e94050a6f12d67 to be a merge! What Git has joined together, let no man put asunder. You may now rebase your PRs.
