### PR TITLE
 0.10/datedetector grave fix

### LINKED ISSUE #1294: Numeric hostname breaks sshd filter
Hello!

I have hostname that is '16950.local'
/var/log/secure will have strings that look like this:

```
Jan 8 16:18:54 16950 sshd[4528]: pam_unix(sshd:session): session opened for user root by (uid=0)
```

timestamp parser throws an error, because it takes hostname as a year. I'm getting errors:

```
2016–01–08 15:50:34,269 fail2ban.filter [1531]: WARNING Found a match for u'Jan 8 15:39:05 16950 sshd[3774]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=27.154.37.285 ' but no valid date/time found for u'Jan 8 15:50:34 1695'. Please try setting a custom date pattern (see man page jail.conf(5)). If format is complex, please file a detailed issue on https://github.com/fail2ban/fail2ban/issues in order to get support for this format.
```

Workaround is to edit filter.d/sshd.conf and put into [Init] section:

`datepattern = ^%%b %%d %%H:%%M:%%S`

### LINKED ISSUE #1548: FreeSwitch: Auth failures not catched for IPv6 address and domains
FreeSwitch filter not catch auth failures for IPv6 address and domains.
Regex not catch failures whe systemd daemon logs used. In this case strings is prepended like
 "Sep 18 04:42:43 fs2.company.org freeswitch[1336]: "

### LINKED ISSUE #1575: Time zones not honored correctly by using datepattern %Z
### Environment:
- Fail2Ban version (including any possible distribution suffixes): 0.9.4
- OS, including release name/version: Ubuntu 14.04.5 LTS
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)
### The issue:

datepattern matching defined in filter but not honored in time calculation
#### Steps to reproduce

I'm trying to get fail2ban to correctly interpret times in the following setup:

1) System time zone is CET/CEST
2) Redmine logs in UTC (hard coded..)
3) fail2ban 0.9.4
4) filters for redmine set correctly, as I understand it; fail2ban correctly matches the line but does not honor the time zone name

The redmine log file to be parsed:

```
root@goegsweb09:/mnt/scratch/fail2ban-0.9.4# cat /mnt/scratch/redmine-production.log 
Started GET "/login?back_url=https%3A%2F%2Fexample.com%2F" for 1.1.1.1 at 2016-10-12 17:56:03 +0200
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"https://example.com/"}
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (4.8ms)
Completed 200 OK in 581ms (Views: 426.6ms | ActiveRecord: 3.5ms)
Started POST "/login" for 1.1.1.1 at 2016-10-12 17:56:25 +0200
Processing by AccountController#login as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"ABCDEFG==", "back_url"=>"https:/example.com/", "username"=>h4xor", "password"=>"[FILTERED]", "login"=>"Login »"}
  Current user: anonymous
Failed login for 'h4xor' from 1.1.1.1 at 2016-10-12 15:56:25 UTC
  Rendered account/login.html.erb within layouts/base (1.2ms)
Completed 200 OK in 68ms (Views: 7.0ms | ActiveRecord: 2.5ms)
```

The filter:

```
root@goegsweb09:/mnt/scratch/fail2ban-0.9.4# sed '/^#/d;/^ *$/d' /etc/fail2ban/filter.d/redmine.conf 
[Definition]
failregex = Failed [-/\w]+ for .* from <HOST>
ignoreregex =
[Init]
datepattern = %%Y-%%m-%%d %%H:%%M:%%S %%Z
```

Debugging the matching process:

```
root@goegsweb09:/mnt/scratch/fail2ban-0.9.4# fail2ban-regex -l debug /mnt/scratch/redmine-production.log /etc/fail2ban/filter.d/redmine.conf

Running tests
=============

D: Setting usedns = warn for Filter(None)
D: Created Filter(None)
Use   failregex filter file : redmine, basedir: /etc/fail2ban
D: Loading configs for filter.d/redmine under /etc/fail2ban 
D: Reading configs for filter.d/redmine under /etc/fail2ban 
D: Reading config files: /etc/fail2ban/filter.d/redmine.conf
D:   Loading files: ['/etc/fail2ban/filter.d/redmine.conf']
D:   Loading files: ['/etc/fail2ban/filter.d/redmine.conf']
D: Date pattern set to `'%Y-%m-%d %H:%M:%S %Z'`: `Year-Month-Day 24hour:Minute:Second Zone name`
D: Date pattern regex for '%Y-%m-%d %H:%M:%S %Z': \b(?P<Y>\d\d\d\d)-(?P<m>1[0-2]|0[1-9]|[1-9])-(?P<d>3[0-1]|[1-2]\d|0[1-9]|[1-9]| [1-9]) (?P<H>2[0-3]|[0-1]\d|\d):(?P<M>[0-5]\d|\d):(?P<S>6[0-1]|[0-5]\d|\d) (?P<Z>cest|utc|cet|gmt)
Use      datepattern : Year-Month-Day 24hour:Minute:Second Zone name
Use         log file : /mnt/scratch/redmine-production.log
Use         encoding : UTF-8

D: Sorting the template list
D: Winning template: Year-Month-Day 24hour:Minute:Second Zone name with 0 hits
D: Matched time template Year-Month-Day 24hour:Minute:Second Zone name
D: Got time 1476280585.000000 for "u'2016-10-12 15:56:25 UTC'" using template Year-Month-Day 24hour:Minute:Second Zone name
D: Sorting the template list
D: Winning template: Year-Month-Day 24hour:Minute:Second Zone name with 1 hits

Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] Failed [-/\w]+ for .* from <HOST>
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] Year-Month-Day 24hour:Minute:Second Zone name
`-

Lines: 13 lines, 0 ignored, 1 matched, 12 missed
[processed in 0.00 sec]

|- Missed line(s):
|  Started GET "/login?back_url=https%3A%2F%2Fexample.com%2F" for 1.1.1.1 at 2016-10-12 17:56:03 +0200
|  Processing by AccountController#login as HTML
|    Parameters: {"back_url"=>"https://example.com/"}
|    Current user: anonymous
|    Rendered account/login.html.erb within layouts/base (4.8ms)
|  Completed 200 OK in 581ms (Views: 426.6ms | ActiveRecord: 3.5ms)
|  Started POST "/login" for 1.1.1.1 at 2016-10-12 17:56:25 +0200
|  Processing by AccountController#login as HTML
|    Parameters: {"utf8"=>"✓", "authenticity_token"=>"ABCDEFG==", "back_url"=>"https:/example.com/", "username"=>h4xor", "password"=>"[FILTERED]", "login"=>"Login »"}
|    Current user: anonymous
|    Rendered account/login.html.erb within layouts/base (1.2ms)
|  Completed 200 OK in 68ms (Views: 7.0ms | ActiveRecord: 2.5ms)
`-
```
#### Expected behavior

Got time should be 1476287785.000000
#### Observed behavior

Time zone "UTC" not honored, got time 1476280585.000000

Checking the resulting time:

```
root@goegsweb09:/mnt/scratch/fail2ban-0.9.4# date -d '@1476280585.000000' -u
Wed Oct 12 13:56:25 UTC 2016
```

### PR DESCRIPTION
**Pull request by sebres**
Fixed ambiguous resp. misleading date detection, if several formats used in log resp. by format switch after restart of some services...

I had long rotated this solution for back and forth, made several attempts to fix resp. optimize it. 
The last straw that broke the camel's back was the try to fix #1548, where the log lines contain dual date time.
This should also fix a possible vulnerability, affected by file-filter only, does not apply to systemd backend (except test-cases), because it uses directly a time from journal record. 
The description of the main problem is a little bit complicated, so hacker thinking expected
_[hacker mode=on]_:
- fail2ban cut out date string (matched datepattern) from each line before it give this line to the filter;
- because the date templates are sorted (by hits) in date detector module, it may cut out the wrong date from log-line (if these are present in log-line, e.g. injecting on some free fields, format switch, etc), so they may be found as first (and correct date will be not found);
- so the fail2ban will overlook this log-line, because the correct date is still present in log-line and it'll never match any specified `failregex` (mostly anchored).
- beyond comes another problem, that some datepatterns are misleading resp. ambiguous and can find date, where it is not.

_[/hacker mode=off]_

---

Here is the last try to fix abovementioned problem (using many different measures)
**WARNING: Theoretically possible backwards incompatibilities** (I cannot judge all the relations in all possible user configurations).
- Misleading date patterns defined more precisely (using extended syntax
  `%Ex[mdHMS]` for exact two-digit match or e. g. `%ExY` as more precise year 
  pattern, within same century of last year and the next 3 years)
- Extends date detector template with distance (position of match in 
  log-line), to prevent grave collision using (re)ordered template list (e.g.
  find-spot of wrong date-match inside foreign input, misleading date patterns
  by ambiguous formats, etc.)
- Distance collision check always prefers template with shortest distance
  (left before right) if date pattern is not anchored
- Fixed UTC/GMT named time zone, using `%Z` and `%z` patterns 
  (special case with 0 zone offset, see gh-1575)
- `filter.d/freeswitch.conf`
  - Optional prefixes (server, daemon, dual time) if systemd daemon logs used (gh-1548)
  - User part rewritten to accept IPv6 resp. domain after "@" (gh-1548)
- More precise date template handling:
  - datedetector rewritten more strict as earlier;
  - default templates can be specified exacter using prefix/suffix syntax (via `datepattern`);
  - more as one date pattern can be specified using option `datepattern` now 
    (new-line separated);
  - some default options like `datepattern` can be specified directly in 
    section `[Definition]`, that avoids contrary usage of unnecessarily `[Init]`
    section, because of performance (each extra section costs time);
  - option `datepattern` can be specified in jail also (e. g. jails without filters 
    or custom log-format, new-line separated for multiple patterns);
  - if first unnamed group specified in pattern, only this will be cut out from
    search log-line (e. g.: `^date:[({DATE})]` will cut out only datetime match 
    pattern, and leaves `date:[] ...` for searching in filter);
  - faster match and fewer searching of appropriate templates
    (DateDetector.matchTime calls rarer DateTemplate.matchDate now);
  - several standard filters extended with exact prefixed or anchored date templates;

Closes #1548
Closes #1575
Closes #1294

The fix was done for 0.10 only, no idea how we could port this to 0.9 without rewriting of half of the code. 
So for 0.9-th branch only solution at moment - to specify (single) exact date pattern per jail (that is always clever).

### CODE REVIEW

**Comment by sebres** [comment]
@fail2ban/contributors This is a huge PR, therefore reviewer are welcome, so please take a look and test it.

@yarikoptic I know, I'm a hacker, really like hacking, etc... (I am not intentionally, it is life ;)

**Comment by yarikoptic** [comment]
wow --  thanks @sebres !  Gimme a few days to digest/analyze it all in some evenings

**Comment by sebres** [comment]
> Gimme a few days to digest/analyze it all in some evenings

@yarikoptic  Could you already take a look?

**Comment by sebres** [comment]
@yarikoptic ping?!

**Comment by yarikoptic** [comment]
Thank you for the pings!!! I will really try in upcoming few days

**Comment by sebres** [comment]
@yarikoptic are 20 days a few days? ;)

I would not annoy, but the "bug" is imho very serious...

I'll resolve conflicts and would like to merge it in 0.10, hereafter make a release ...
Thoughts?

**Comment by yarikoptic** [comment]
Heh... Sorry... Should have looked at it over past weekend but didn't ... I'd no reply by Wed, merge I guess

File: config/filter.d/3proxy.conf [hunk 1]
```diff
@@ -9,6 +9,8 @@ failregex = ^\s[+-]\d{4} \S+ \d{3}0[1-9] \S+ <HOST>:\d+ [\d.]+:\d+ \d+ \d+ \d+\s
 
 ignoreregex = 
 
+datepattern = {^LN-BEG}
```
Comment (yarikoptic) [inline config/filter.d/3proxy.conf]: btw where do we have description of those ? (`{^LN-BEG}`, `{DATE}`)
